# Generated by Django 5.1 on 2026-04-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, upload_to="authors/")),
                ("website", models.URLField(blank=True)),
                ("twitter", models.CharField(blank=True, max_length=50)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="author", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
            ],
            options={"verbose_name_plural": "categories"},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("excerpt", models.TextField(blank=True, max_length=300)),
                ("content", models.TextField()),
                ("featured_image", models.ImageField(blank=True, upload_to="posts/%Y/%m/")),
                ("featured_image_alt", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], default="draft", max_length=10)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("reading_time", models.PositiveIntegerField(default=0, editable=False)),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_image", models.ImageField(blank=True, upload_to="og/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="posts", to="blog.author")),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="posts", to="blog.category")),
                ("tags", models.ManyToManyField(blank=True, related_name="posts", to="blog.tag")),
            ],
            options={"ordering": ["-published_at"]},
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="blog_post_slug_d6fe4b_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status", "published_at"], name="blog_post_status_7f8b3f_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["is_featured"], name="blog_post_is_feat_ef69d3_idx"),
        ),
    ]
