# Generated by Django 5.2.13 on 2026-04-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_slug_cdb902_idx',
            old_name='blog_post_slug_d6fe4b_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_status_5b2843_idx',
            old_name='blog_post_status_7f8b3f_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_is_feat_837e2e_idx',
            old_name='blog_post_is_feat_ef69d3_idx',
        ),
    ]
