# Generated by Django 5.2.13 on 2026-04-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='credentials',
            field=models.CharField(blank=True, help_text='Academic or professional credentials (e.g. PhD, Senior AI Architect)', max_length=255),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
