# Generated by Django 5.2.13 on 2026-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_credentials_author_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('america', 'America'), ('europe', 'Europe'), ('asia', 'Asia')], default='global', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('america', 'America'), ('europe', 'Europe'), ('asia', 'Asia')], default='global', max_length=10),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['region'], name='blog_post_region_4c669f_idx'),
        ),
    ]
