# Generated by Django 5.1 on 2026-04-25 00:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed", models.BooleanField(default=False)),
                ("confirmation_token", models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["email", "is_active"], name="newsletter__email_9b2f33_idx"),
        ),
    ]
