# Generated by Django 5.2.13 on 2026-04-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriber',
            new_name='newsletter__email_273e90_idx',
            old_name='newsletter__email_9b2f33_idx',
        ),
    ]
