# Generated by Django 5.2.13 on 2026-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_rename_newsletter__email_9b2f33_idx_newsletter__email_273e90_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='region',
            field=models.CharField(choices=[('global', 'Global'), ('america', 'America'), ('europe', 'Europe'), ('asia', 'Asia')], default='global', max_length=10),
        ),
    ]
